const male_default =
  "https://cdn.vectorstock.com/i/500p/70/01/default-male-avatar-profile-icon-grey-photo-vector-31827001.jpg";
const female_default =
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSaZDgyPDcrmLhfo3c2l1aB9FZfmKu8EDuH2A&s";

const data_students = [
  {
    name: "Aryan Singh",
    reg_no: "23BEE0001",
    school: "SELECT",
    contactNo: 9876543210,
    hostel: "A-Block Mens Hostel",
    cgpa: 8.6,
    image: male_default,
  },
  {
    name: "Tanisha Reddy",
    reg_no: "23BEC0014",
    school: "SENSE",
    contactNo: 9876543343,
    hostel: "L-Block Ladies Hostel",
    cgpa: 9.0,
    image: female_default,
  },
  {
    name: "Ananya Roy",
    reg_no: "23BEE0006",
    school: "SELECT",
    contactNo: 9876543265,
    hostel: "F-Block Ladies Hostel",
    cgpa: 9.0,
    image: female_default,
  },
  {
    name: "Yash Khanna",
    reg_no: "23BEE0021",
    school: "SELECT",
    contactNo: 9876543410,
    hostel: "S-Block Mens Hostel",
    cgpa: 7.9,
    image: male_default,
  },
  {
    name: "Pooja Iyer",
    reg_no: "23BCS0022",
    school: "SCOPE",
    contactNo: 9876543421,
    hostel: "T-Block Ladies Hostel",
    cgpa: 9.3,
    image: female_default,
  },
  {
    name: "Ritika Gupta",
    reg_no: "23BEE0010",
    school: "SELECT",
    contactNo: 9876543309,
    hostel: "J-Block Ladies Hostel",
    cgpa: 8.9,
    image: female_default,
  },
  {
    name: "Rajeev Menon",
    reg_no: "23BCS0015",
    school: "SCOPE",
    contactNo: 9876543354,
    hostel: "M-Block Mens Hostel",
    cgpa: 7.6,
    image: male_default,
  },
  {
    name: "Megha Das",
    reg_no: "23BEE0012",
    school: "SELECT",
    contactNo: 9876543321,
    hostel: "B-Block Ladies Hostel",
    cgpa: 9.2,
    image: female_default,
  },
  {
    name: "Aman Yadav",
    reg_no: "23BCS0013",
    school: "SCOPE",
    contactNo: 9876543332,
    hostel: "K-Block Mens Hostel",
    cgpa: 8.8,
    image: male_default,
  },
  {
    name: "Sneha Patil",
    reg_no: "23BCS0024",
    school: "SCOPE",
    contactNo: 9876543443,
    hostel: "B-Block Ladies Hostel",
    cgpa: 9.2,
    image: female_default,
  },
  {
    name: "Kunal Mehta",
    reg_no: "23BEE0007",
    school: "SELECT",
    contactNo: 9876543276,
    hostel: "G-Block Mens Hostel",
    cgpa: 8.1,
    image: male_default,
  },
  {
    name: "Simran Chawla",
    reg_no: "23BCS0030",
    school: "SCOPE",
    contactNo: 9876543509,
    hostel: "H-Block Ladies Hostel",
    cgpa: 9.5,
    image: female_default,
  },
  {
    name: "Shruti Mishra",
    reg_no: "23BEC0016",
    school: "SENSE",
    contactNo: 9876543365,
    hostel: "N-Block Ladies Hostel",
    cgpa: 8.9,
    image: female_default,
  },
  {
    name: "Aditya Tiwari",
    reg_no: "23BEE0011",
    school: "SELECT",
    contactNo: 9876543310,
    hostel: "A-Block Mens Hostel",
    cgpa: 8.3,
    image: male_default,
  },
  {
    name: "Parth Aggarwal",
    reg_no: "23BCS0017",
    school: "SCOPE",
    contactNo: 9876543376,
    hostel: "O-Block Mens Hostel",
    cgpa: 8.3,
    image: male_default,
  },
  {
    name: "Kritika Anand",
    reg_no: "23BEE0028",
    school: "SELECT",
    contactNo: 9876543487,
    hostel: "F-Block Ladies Hostel",
    cgpa: 8.9,
    image: female_default,
  },
  {
    name: "Sanya Kapoor",
    reg_no: "23BEE0008",
    school: "SELECT",
    contactNo: 9876543287,
    hostel: "H-Block Ladies Hostel",
    cgpa: 8.7,
    image: female_default,
  },
  {
    name: "Manan Kapoor",
    reg_no: "23BCS0027",
    school: "SCOPE",
    contactNo: 9876543476,
    hostel: "E-Block Mens Hostel",
    cgpa: 7.4,
    image: male_default,
  },
  {
    name: "Neha Joshi",
    reg_no: "23BCS0032",
    school: "SCOPE",
    contactNo: 9876543521,
    hostel: "J-Block Ladies Hostel",
    cgpa: 9.0,
    image: female_default,
  },
  {
    name: "Rohan Verma",
    reg_no: "23BEE0003",
    school: "SELECT",
    contactNo: 9876543232,
    hostel: "C-Block Mens Hostel",
    cgpa: 7.8,
    image: male_default,
  },
  {
    name: "Aarushi Sen",
    reg_no: "23BEC0026",
    school: "SENSE",
    contactNo: 9876543465,
    hostel: "D-Block Ladies Hostel",
    cgpa: 8.8,
    image: female_default,
  },
  {
    name: "Kabir Malhotra",
    reg_no: "23BCS0019",
    school: "SCOPE",
    contactNo: 9876543398,
    hostel: "Q-Block Mens Hostel",
    cgpa: 9.1,
    image: male_default,
  },
  {
    name: "Divya Chauhan",
    reg_no: "23BEE0018",
    school: "SELECT",
    contactNo: 9876543387,
    hostel: "P-Block Ladies Hostel",
    cgpa: 8.4,
    image: female_default,
  },
  {
    name: "Siddharth Jain",
    reg_no: "23BEE0005",
    school: "SELECT",
    contactNo: 9876543254,
    hostel: "E-Block Mens Hostel",
    cgpa: 8.2,
    image: male_default,
  },
  {
    name: "Niharika Sharma",
    reg_no: "23BEE0002",
    school: "SELECT",
    contactNo: 9876543221,
    hostel: "B-Block Ladies Hostel",
    cgpa: 9.1,
    image: female_default,
  },
  {
    name: "Arjun Rathi",
    reg_no: "23BEC0029",
    school: "SENSE",
    contactNo: 9876543498,
    hostel: "G-Block Mens Hostel",
    cgpa: 8.6,
    image: male_default,
  },
  {
    name: "Priya Nair",
    reg_no: "23BEE0004",
    school: "SELECT",
    contactNo: 9876543243,
    hostel: "D-Block Ladies Hostel",
    cgpa: 8.4,
    image: female_default,
  },
  {
    name: "Devansh Bhatt",
    reg_no: "23BEE0025",
    school: "SELECT",
    contactNo: 9876543454,
    hostel: "C-Block Mens Hostel",
    cgpa: 8.5,
    image: male_default,
  },
  {
    name: "Rhea Pillai",
    reg_no: "23BEC0020",
    school: "SENSE",
    contactNo: 9876543409,
    hostel: "R-Block Ladies Hostel",
    cgpa: 8.7,
    image: female_default,
  },
  {
    name: "Vivek Rana",
    reg_no: "23BEE0009",
    school: "SELECT",
    contactNo: 9876543298,
    hostel: "I-Block Mens Hostel",
    cgpa: 7.5,
    image: male_default,
  },
  {
    name: "Anshul Deshmukh",
    reg_no: "23BEC0023",
    school: "SENSE",
    contactNo: 9876543432,
    hostel: "U-Block Mens Hostel",
    cgpa: 8.0,
    image: male_default,
  },
  {
    name: "Harsh Vardhan",
    reg_no: "23BEE0031",
    school: "SELECT",
    contactNo: 9876543510,
    hostel: "I-Block Mens Hostel",
    cgpa: 8.1,
    image: male_default,
  },
];

module.exports = { data_students };
